In [105]:
import pandas as pd
import numpy as np
import os

In [106]:
# Store filepath in a variable
school_data = os.path.join('schools_complete.csv')
student_data = os.path.join('students_complete.csv')

In [107]:
# Read our Datafile with the pandas Library
school_data_pd = pd.read_csv(school_data)
student_data_pd = pd.read_csv(student_data)
school_data_pd = school_data_pd.rename(columns={'name':'school_name'})
student_data_pd = student_data_pd.rename(columns={'school':'school_name'})
district_data_pd = pd.merge(student_data_pd, school_data_pd, how="inner")
district_data_pd.head(17)

,Student ID,name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
5,5,Bryan Miranda,M,9th,Huang High School,94,94,0,District,2917,1910635
6,6,Sheena Carter,F,11th,Huang High School,82,80,0,District,2917,1910635
7,7,Nicole Baker,F,12th,Huang High School,96,69,0,District,2917,1910635
8,8,Michael Roth,M,10th,Huang High School,95,87,0,District,2917,1910635
9,9,Matthew Greene,M,10th,Huang High School,96,84,0,District,2917,1910635
10,10,Andrew Alexander,M,10th,Huang High School,90,70,0,District,2917,1910635
11,11,Daniel Cooper,M,10th,Huang High School,78,77,0,District,2917,1910635
12,12,Brittney Walker,F,9th,Huang High School,64,79,0,District,2917,1910635
13,13,William Long,M,9th,Huang High School,71,79,0,District,2917,1910635
14,14,Tammy Hebert,F,10th,Huang High School,85,67,0,District,2917,1910635
15,15,Dr. Jordan Carson,M,11th,Huang High School,94,88,0,District,2917,1910635
16,16,Donald Zamora,M,9th,Huang High School,88,55,0,District,2917,1910635

In [108]:
Columns = ['Total Schools', 'Total students', 'Total Budget', 'Average Math Score', 'Average Reading Score', '% Passing Math', 
          '% Passing Reading', '% Overall Passing Rate']

total_schools = district_data_pd['school_name'].nunique()
total_students = district_data_pd['Student ID'].nunique()
total_budget = school_data_pd['budget'].sum()
avg_math_score = district_data_pd['math_score'].mean()
avg_reading_score = district_data_pd['reading_score'].mean()

passing_math_count = district_data_pd[(district_data_pd['math_score']>70)].count()['name']
passing_reading_count = district_data_pd[(district_data_pd['reading_score']>70)].count()['name']

perc_passing_math = (passing_math_count/total_students) * 100
perc_passing_reading = (passing_reading_count/total_students) *100
perc_passing_overall = (perc_passing_math + perc_passing_reading)/2

Values = [total_schools, total_students, total_budget, avg_math_score, avg_reading_score, perc_passing_math, perc_passing_reading, perc_passing_overall]

District_Summary = pd.DataFrame([Values], columns=Columns)
District_Summary = District_Summary.round(2)
District_Summary

,Total Schools,Total students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
0,15,39170,24649428,78.99,81.88,72.39,82.97,77.68

In [109]:
grouped_student_school_data_pd = student_data_pd.groupby(['school_name'], as_index=False)
#grouped_student_school_data_pd.head(5)

In [111]:
school_avg_math_pd = pd.DataFrame(grouped_student_school_data_pd['math_score'].mean())
school_avg_math_pd.head()

            school_name  math_score
0    Bailey High School   77.048432
1   Cabrera High School   83.061895
2  Figueroa High School   76.711767
3      Ford High School   77.102592
4   Griffin High School   83.351499

,Student ID,name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
4,4,Bonnie Ray,F,9th,Huang High School,97,84
5,5,Bryan Miranda,M,9th,Huang High School,94,94
6,6,Sheena Carter,F,11th,Huang High School,82,80
8,8,Michael Roth,M,10th,Huang High School,95,87
2917,2917,Amy Jacobs,F,10th,Figueroa High School,85,87
2918,2918,Nathan Campbell,M,12th,Figueroa High School,97,84
2919,2919,Randall Stewart,M,12th,Figueroa High School,67,77
2922,2922,Amanda Hamilton DDS,F,9th,Figueroa High School,72,93
2923,2923,Anthony Pace,M,10th,Figueroa High School,66,90
5866,5866,Jamie Montgomery,F,12th,Shelton High School,70,91
5867,5867,Shannon Phillips,F,10th,Shelton High School,84,71
5868,5868,Todd Barber,M,11th,Shelton High School,95,99
5869,5869,Desiree King,F,12th,Shelton High School,76,95
5870,5870,Melissa Roberts,F,10th,Shelton High School,71,82
7627,7627,Russell Davis,M,10th,Hernandez High School,70,88
7628,7628,Timothy Walker,M,12th,Hernandez High School,97,93
7629,7629,Katie Johnston,F,12th,Hernandez High School,83,81
7630,7630,Joann Oconnell,F,12th,Hernandez High School,77,91
7631,7631,Sarah Alexander,F,10th,Hernandez High School,84,93
12263,12263,Elizabeth Goodwin,F,10th,Griffin High School,91,81
12264,12264,Michelle Wong,F,9th,Griffin High School,78,89
12265,12265,Scott Roth MD,M,11th,Griffin High School,91,85
12266,12266,Billy Wilson,M,12th,Griffin High School,76,83
12267,12267,Robert Lane,M,11th,Griffin High School,76,71
13730,13730,Kelli Anderson,F,10th,Wilson High School,84,71
13731,13731,Russell Ramirez,M,10th,Wilson High School,72,87
13732,13732,Eric Butler,M,10th,Wilson High School,97,82
13734,13734,Gail Hall,F,9th,Wilson High School,79,72
13735,13735,Angela Walters,F,9th,Wilson High School,80,91
...,...,...,...,...,...,...,...
23274,23274,Alec Davis,M,9th,Pena High School,91,75
23275,23275,Michael Meyer,M,10th,Pena High School,94,76
23276,23276,Donald Gutierrez,M,11th,Pena High School,98,91
23277,23277,Travis Chavez,M,11th,Pena High School,78,71
23278,23278,Sheena Ball,F,12th,Pena High School,87,92
24236,24236,Aaron Johnson,M,10th,Wright High School,89,72
24237,24237,Kimberly Hamilton,F,10th,Wright High School,84,93
24238,24238,Ashley Johns,F,10th,Wright High School,88,88
24239,24239,Stephanie Donovan,F,10th,Wright High School,75,84
24240,24240,Cynthia Guzman,F,11th,Wright High School,93,82
26036,26036,Sherry Jenkins,F,11th,Rodriguez High School,74,81
26037,26037,Kimberly Calderon,F,10th,Rodriguez High School,80,86
26039,26039,Jacob Padilla,M,11th,Rodriguez High School,79,73
26040,26040,Paula Maldonado,F,10th,Rodriguez High School,96,92
26041,26041,Patricia Escobar,F,12th,Rodriguez High School,68,98
30035,30035,Lisa Casey,F,12th,Johnson High School,87,87
30037,30037,Anna Wilkins,F,11th,Johnson High School,89,77
30038,30038,Andrew Smith,M,9th,Johnson High School,66,85
30039,30039,Robert Allison,M,11th,Johnson High School,63,85
30040,30040,Andrew Wilson,M,11th,Johnson High School,70,84
34796,34796,Michael Mercado,M,9th,Ford High School,66,94
34801,34801,Mr. William Scott,M,9th,Ford High School,73,75
34803,34803,Steven Lee,M,9th,Ford High School,77,84
34805,34805,Veronica English,F,9th,Ford High School,75,93
34806,34806,Crystal Sandoval,F,11th,Ford High School,85,84
37535,37535,Norma Mata,F,10th,Thomas High School,76,76
37536,37536,Cody Miller,M,11th,Thomas High School,84,82
37537,37537,Erik Snyder,M,9th,Thomas High School,80,90
37539,37539,Noah Erickson,M,9th,Thomas High School,86,76
37540,37540,Austin Meyer,M,9th,Thomas High School,73,96